channels:
- defaults
dependencies:
- python=3.6.2
- jupyter_client=5.1.0
- jupyter_core=4.3.0
- matplotlib>=2.0,<2.1
- scipy>=0.19,<0.20
- numpy>=1.13,<1.14
- pip:
  - qiskit==0.4.11
  - IBMQuantumExperience>=1.8.26
